### ISSUE TITLE
Hi, is a 1.18 version possible? I would absolutely LOVE to play with this mod! 

### ISSUE THREAD

**Issue by EysseW** [andrewathalye/anaglyph-fabric#1]

**Comment by vlad2305m** [comment]
I made my own from scratch and only then found this one.
https://github.com/vlad2305m/Anaglyph-fabric

**Comment by andrewathalye** [comment]
I did a quick check, and no changes were required to use on 1.18.2, so I've pushed an update for that. Sorry about not reading your issue for a while. I anticipate the same will be the case for 1.19.X, but I don't intend to support that for now because of the uncertainties involving global bans. Once the situation with that is cleared up I'll gladly make a release for that as well.
